title: Kiran Chakkilam 
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/kiranchakkilam" color:orange>LinkedIn</a> |
  <a href="https://github.com/kiranupgrad" color:orange>GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Working in Mavenir as part of QA/Automation  team.
  Working in Telecom domain for more than 15 years.
  <br>
  </p>
google_analytics:
theme: jekyll-theme-cayman
